changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: "Features"
      labels:
        - feature
        - feat
    - title: "Bug Fixes"
      labels:
        - fix
    - title: "Refactoring"
      labels:
        - refactor
    - title: "Documentation"
      labels:
        - docs
    - title: "Infrastructure"
      labels:
        - chore
        - build
        - ci
    - title: "Other Changes"
      labels:
        - "*"
