export {
  ThemeService,
  BUILTIN_THEMES,
  DEFAULT_THEME_ID,
  THEME_ID_DARK,
  THEME_ID_GRAPHITE,
  THEME_ID_LIGHT,
  THEME_ID_SEPIA,
  type ThemeId,
  type TThemeColors,
  type TThemeDefinition,
  type TThemeServiceArgs,
  type TThemeServiceHooks,
  fxGetThemeCssVariables,
  txApplyThemeToElement,
} from "@vibecanvas/service-theme";
