export const ProjectFsErr = {
  FILE_TREE_PATH_NOT_FOUND: "FX.PROJECT_FS.FILE_TREE.PATH_NOT_FOUND",
  FILE_TREE_EXEC_FAILED: "FX.PROJECT_FS.FILE_TREE.EXEC_FAILED",
  PROJECT_ROOT_CLAUDE_NOT_FOUND: "FX.PROJECT_FS.PROJECT_ROOT.CLAUDE_NOT_FOUND",
  PROJECT_ROOT_GIT_NOT_FOUND: "FX.PROJECT_FS.PROJECT_ROOT.GIT_NOT_FOUND",
} as const satisfies Record<string, TErrorCode>;
