export const ConfigErr = {
  CONFIG_PATH_CREATE_FAILED: "TX.CONFIG.CONFIG_PATH.CREATE_FAILED",
  XDG_PATHS_MONOREPO_NOT_FOUND: "FN.CONFIG.XDG_PATHS.MONOREPO_NOT_FOUND",
  ENSURE_DIRS_FAILED: "TX.CONFIG.ENSURE_DIRS.FAILED",
} as const satisfies Record<string, TErrorCode>;
